name: Collaboration task
description: Identify a collaboration between this development team and another party. e.g, A support case, dependency effort,etc
title: "[Collaboration] <title> "
labels: [Collaboration]
assignees:
  - IBMAnsibleHelper
body:
  - type: markdown
    attributes:
      value: |
        Before authoring a task, please review existing issues to avoid duplication.
        ---
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: There are no existing issues.
      required: true
  - type: checkboxes
    id: support-issue
    attributes:
      label: Support and service?
      description: Is support and service involved in this collaboration
    options:
    - label: Yes, support and service is involved.
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Collaboration description
      description: Describe the task, this is the equivalent of a agile story.
      placeholder: Verbosity is encouraged, the more you share the better for us to understand.
    validations:
      required: true
  - type: textarea
    id: collaborators
    attributes:
      label: collaborators
      description: Who or what product is part of this collaboration.
      placeholder: GH IDs, product, etc
    validations:
      required: true
  - type: dropdown
    id: modules
    attributes:
      label: Ansible module
      description: Select which modules are being reported for this task. You can select more than one.
      multiple: true
      options:
        - zos_apf
        - zos_backup_restore
        - zos_blockinfile
        - zos_copy
        - zos_data_set
        - zos_encode
        - zos_fetch
        - zos_find
        - zos_gather_facts
        - zos_job_output
        - zos_job_query
        - zos_job_submit
        - zos_lineinfile
        - zos_mount
        - zos_mvs_raw
        - zos_operator
        - zos_operator_action_query
        - zos_ping
        - zos_tso_command
    validations:
      required: false
