blank_issues_enabled: false
contact_links:
  - name: GitHub Community Support
    url: https://github.com/ansible-collections/ibm_zos_core/discussions
    about: Please ask and answer questions here.
