name: Report a documentation issue
description: Request that documentation be reviewed.
title: "[Documentation]: <title> "
labels: [Documentation]
assignees:
  - IBMAnsibleHelper
body:
  - type: markdown
    attributes:
      value: |
        Before reporting a documentation issue, please review existing isssues to avoid duplication.
        ---
  - type: textarea
    id: issue-description
    attributes:
      label: Documentation issue description
      description: Describe the documentation issue.
      placeholder: |
        Verbosity is encouraged, the more you share the better for us to understand.
          1. Include links to the page you are reffering to if applicable
          2. Include reproduction steps if applicable
          3. Include any additional information that will help us
          4. Include screen captures of applicable
          5. Include browser or shell if applicable
    validations:
      required: true
  - type: textarea
    id: ansible-version
    attributes:
      label: Ansible version
      description: What is the verson of Ansible on the controller if applicable.
      placeholder: Paste verbatim output from `ansible --version`.
      render: SHELL
    validations:
      required: false
  - type: dropdown
    id: collection-version
    attributes:
      label: IBM z/OS Ansible core Version
      description: |
        Which version of the z/OS Ansible core collection are you using. If you are unsure, run the command: `cat ~/.ansible/collections/ansible_collections/ibm/ibm_zos_core/MANIFEST.json | grep version`
      options:
        - v1.0.0
        - v1.1.0
        - v1.2.1
        - v1.3.0
        - v1.3.1
        - v1.3.3
        - v1.3.5
        - v1.3.6
        - v1.4.0-beta.1
        - v1.4.0-beta.2
    validations:
      required: true
  - type: checkboxes
    id: modules
    attributes:
      label: Ansible module
      description: Select which modules are being reported in this bug.
      options:
        - label: zos_apf
          required: false
        - label: zos_backup_restore
          required: false
        - label: zos_blockinfile
          required: false
        - label: zos_copy
          required: false
        - label: zos_data_set
          required: false
        - label: zos_encode
          required: false
        - label: zos_fetch
          required: false
        - label: zos_find
          required: false
        - label: zos_gather_facts
          required: false
        - label: zos_job_output
          required: false
        - label: zos_job_query
          required: false
        - label: zos_job_submit
          required: false
        - label: zos_lineinfile
          required: false
        - label: zos_mount
          required: false
        - label: zos_mvs_raw
          required: false
        - label: zos_operator
          required: false
        - label: zos_operator_action_query
          required: false
        - label: zos_ping
          required: false
        - label: zos_tso_command
          required: false
    validations:
      required: false
