name: Enhancement Issue
description: Request that existing collection content be enhnanced.
title: "[Enhancement]: <title> "
labels: [Enhancement]
assignees:
  - IBMAnsibleHelper
body:
- type: markdown
  attributes:
    value: |
      Before requesting an enhancement, please review existing isssues to avoid duplication.
      ---
- type: textarea
  id: issue-description
  attributes:
    label: Enhancement description
    description: Describe the enhancement you are requesting.
    placeholder: Verbosity is encouraged, the more you share the better for us to understand.
  validations:
    required: true