name: Request a new feature
description: Request new collection content be created.
title: "[New Feature] <title> "
labels: [New Feature]
assignees:
  - IBMAnsibleHelper
body:
  - type: markdown
    attributes:
      value: |
        Before requesting a new feature, please review existing isssues to avoid duplication.
        ---
  - type: textarea
    id: issue-description
    attributes:
      label: New feature description
      description: Describe the new feature you are requesting.
      placeholder: Verbosity is encouraged, the more you share the better for us to understand.
    validations:
      required: true
  - type: textarea
    id: user-story
    attributes:
      label: User story
      description: Write a user story with emphasis on the persona, for example sysadmin.
      placeholder: |
        Verbosity is encouraged, the more you share the better for us to understand.
        User stories take this form:
          - As a < type of user >, I want < some goal > so that < some reason >.
        Examples:
          - As a z/OS System Admin, I can grow zFS aggregates with Ansible so that my data sets don't fill up.
          - As a Junior developer, I want to be able to zip and unzip arives using Ansible, so that I don't have to perform operations elsewhere.
    validations:
      required: false
